export const LOGIN_USER = "LOGIN_USER"
export const REGISTER_USER = "REGISTER_USER"
export const UPDATE_USER = "UPDATE_USER"
export const LOGOUT_USER = "LOGOUT_USER"
export const AUTH_USER = "AUTH_USER"
export const PRODUCT_DETAIL = "PRODUCT_DETAIL"
export const PRODUCT_UPDATE = 'PRODUCT_UPDATE'